name: Perfect Code Check
on: [push]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.1-focal
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }
      - name: Install Deps
        run: npm install
      - name: Run Background Tests
        run: npx playwright test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
